service: hello-world-node

provider:
 name: aws
 runtime: nodejs12.x
 memorySize: 256
 timeout: 10
 stage: production
 region: eu-central-1

functions:
 api:
   handler: lambda.universal
   events:
     - http: ANY {proxy+}
     - http: ANY /